version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6378:6379'
  postgres-db:
    image: postgres:16
    container_name:
      postgres-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL",'sh -c "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  django-app:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "sleep 3 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8008'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres-db:
        condition: service_healthy
  celery:
      build: .
      tty: true
      env_file:
        - .env
      command: celery --app=backend worker --loglevel=info --pool=solo
      depends_on:
          - redis
          - django-app

